version: '3.8'
services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: books
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app-network
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo_admin:password@mongo:27017/?authSource=admin
    networks:
      - app-network
    volumes:
      - ./:/app

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data: